//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Identity.Api.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Identity.Api.Resources.MessageResources", typeof(MessageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to authenticate you now, please contact the support team..
        /// </summary>
        public static string AuthImpossible {
            get {
                return ResourceManager.GetString("AuthImpossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your authentification request is empty..
        /// </summary>
        public static string AuthRequestEmpty {
            get {
                return ResourceManager.GetString("AuthRequestEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get all roles, please contact the support team..
        /// </summary>
        public static string FetchingAllRolesFailed {
            get {
                return ResourceManager.GetString("FetchingAllRolesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get all users, please contact the support team..
        /// </summary>
        public static string FetchingAllUsersFailed {
            get {
                return ResourceManager.GetString("FetchingAllUsersFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to re-initialize user password now, please contact the support team..
        /// </summary>
        public static string PasswordReinitFailed {
            get {
                return ResourceManager.GetString("PasswordReinitFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password re-initialization request is empty..
        /// </summary>
        public static string PasswordReinitRequestEmpty {
            get {
                return ResourceManager.GetString("PasswordReinitRequestEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update your password now, please contact the support team..
        /// </summary>
        public static string PasswordUpdateFailed {
            get {
                return ResourceManager.GetString("PasswordUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password update request is empty..
        /// </summary>
        public static string PasswordUpdateRequestEmpty {
            get {
                return ResourceManager.GetString("PasswordUpdateRequestEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to assign the specified role to your user now, please contact the support team..
        /// </summary>
        public static string RoleAssignmentFailed {
            get {
                return ResourceManager.GetString("RoleAssignmentFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your user role assignment request is empty..
        /// </summary>
        public static string RoleAssignmentRequestEmpty {
            get {
                return ResourceManager.GetString("RoleAssignmentRequestEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your user role unassignment request is empty..
        /// </summary>
        public static string RoleUnassignmentRequestEmpty {
            get {
                return ResourceManager.GetString("RoleUnassignmentRequestEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to unassign the specific user from role now, please contact the support team..
        /// </summary>
        public static string RoleUnassignmentRequestFailed {
            get {
                return ResourceManager.GetString("RoleUnassignmentRequestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create a new user now, please contact the support team..
        /// </summary>
        public static string UserCreationFailed {
            get {
                return ResourceManager.GetString("UserCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your user creation request is empty..
        /// </summary>
        public static string UserCreationRequestEmpty {
            get {
                return ResourceManager.GetString("UserCreationRequestEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete your user now, please contact the support team..
        /// </summary>
        public static string UserDeletionFailed {
            get {
                return ResourceManager.GetString("UserDeletionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must provide a login to delete a user..
        /// </summary>
        public static string UserDeletionRequestEmpty {
            get {
                return ResourceManager.GetString("UserDeletionRequestEmpty", resourceCulture);
            }
        }
    }
}
